Refactor rebuild_proxies to separate resolution and auth handling
psf/requests pull request #5924
Opened 2021-09-02 06:01 UTC by nateprewitt

This is a proposal for handling #5888 that's come out of discussion in an alternative PR (#5893). Given that we've stalled out on progress there for a few weeks, this PR is to help drive a conclusion. The approach taken here is to mitigate the incorrect behavior of stripping `Proxy-Authorization` headers off all requests send with `Session.send`. This will not address the performance concerns from #5891 as that's a more significant problem without a clear answer.

The goal of driving this separately from #5891 is that one is an unintended breakage in basic behavior of the library and the second is an unfortunate performance regression. I'd like to address the former more quickly if possible instead of letting the problem fester.

2021-09-02 17:03 UTC, omermizr commented
Hey @nateprewitt, thanks for this!
I added a few comments following up on our discussions.

2021-09-02 17:04 UTC, omermizr reviewed
Hey @nateprewitt, thanks for this!
I added a few comments following up on our discussions.

2021-09-02 17:04 UTC, omermizr commented on requests/sessions.py
> +        if 'proxies' not in kwargs:
This change should actually fix the performance regression in most cases (`Session.request` - which I assume is the most common flow - always sets `proxies` on `kwargs`).

2021-09-02 17:04 UTC, omermizr commented on requests/sessions.py
> +            kwargs['proxies'] = resolve_proxies(
So now we're:
1. No longer stripping the proxy-auth header. Sounds right to me.
2. No longer setting the proxy-auth header at all. Is this the desired behavior? What if someone uses a proxy and passes the username + password in the url? (though I'm not sure if that flow is supported or not)

2021-09-02 17:04 UTC, omermizr commented on requests/utils.py
> +    bypass_proxy = should_bypass_proxies(url, no_proxy=no_proxy)
Didn't we want to unify 850 and 851 so we don't call `should_bypass_proxies` if `trust_env` is `False`?

2021-09-02 17:13 UTC, nateprewitt commented on requests/sessions.py
> +            kwargs['proxies'] = resolve_proxies(
For 2.) we were never doing that before this change and I don't think that was an intended byproduct. We should still support our normal proxy auth flows that were available prior to #5681.

2021-09-02 17:14 UTC, nateprewitt commented on requests/utils.py
> +    bypass_proxy = should_bypass_proxies(url, no_proxy=no_proxy)
We do, I was going to have @dbaxa rebase their change onto whatever we merge so they can still have a commit in the repo.

2021-09-02 17:16 UTC, nateprewitt commented on requests/sessions.py
> +        if 'proxies' not in kwargs:
Yep, I think `proxies` will be the escape hatch when performance is a concern here :)

2021-09-05 03:46 UTC, Tabbbbs requested changes
[](https://github.com/psf/requests/pull/5924/files)

2021-09-08 04:23 UTC, dbaxa commented on requests/utils.py
> +    bypass_proxy = should_bypass_proxies(url, no_proxy=no_proxy)
Sounds good to me.

2021-09-08 04:23 UTC, dbaxa approved these changes

2021-09-13 04:06 UTC, dbaxa commented
When can we merge this @nateprewitt ?

2021-09-13 17:11 UTC, nateprewitt commented
I believe we're waiting on either some consensus with this proposal or feedback for another direction. @sigmavirus24/@sethmlarson, do you have any thoughts on how we proceed with #5888?

2021-11-24 19:17 UTC, sigmavirus24 approved these changes

2021-11-24 19:21 UTC, merged