Update models.Response.json docstring clearer
psf/requests pull request #6529
Opened 2023-09-14 09:01 UTC by anupam-arista

2024-04-04 13:16 UTC, achapkowski commented
I know I'm not an admin, but this doc string change is a solid change could it be merged?

2024-12-12 23:53 UTC, anupam-arista commented
I spent like 1 hour because these 2 words were pointing the wrong way

2025-02-11 11:55 UTC, sigmavirus24 requested changes

2025-02-11 11:55 UTC, sigmavirus24 commented on src/requests/models.py
> +        r"""Returns the json-decoded dict of a response, if any.
```suggestion
        r"""Decodes the JSON response body (if any) as a Python object.

           This may return a dictionary, list, etc. depending on what is in the response.
```

2025-02-12 11:57 UTC, sigmavirus24 commented on src/requests/models.py
> +        r"""Decodes the JSON response body (if any) as a Python object.
```suggestion
        r"""Decodes the JSON response body (if any) as a Python object.

```

2025-02-12 21:58 UTC, sigmavirus24 approved these changes

2025-02-13 16:49 UTC, nateprewitt approved these changes

2025-02-13 16:49 UTC, merged